name: modern_music_player
description: Offline music player app for Android.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.40
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.10.0
  intl: ^0.19.0
  audio_session: ^0.1.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
